# Generated by Django 3.2.9 on 2021-12-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telesettings',
            name='tg_message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
