# Generated by Django 3.2.9 on 2021-12-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='sliderimg/')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('css', models.CharField(default='-', max_length=250, null=True, verbose_name='Осн. картинка?')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
