# Generated by Django 3.2.9 on 2021-12-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0002_scrollslider_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrollslider',
            name='css',
            field=models.CharField(max_length=250, null=True, verbose_name='Осн. картинка'),
        ),
    ]
