# Generated by Django 3.2.9 on 2021-12-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll', '0003_alter_scrollslider_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrollslider',
            name='css',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Осн. картинка?'),
        ),
    ]
